### ISSUE TITLE
Errors in move validation?

### ISSUE THREAD

**Issue by ganthern** [mkeeter/pont#1]
I'm not sure if I simply misunderstood the rules, but this move:

![pont](https://user-images.githubusercontent.com/29049728/84064671-5059ca00-a9c3-11ea-945d-9a62a2465e8b.png)

seems to break the "contribute to one connected row or column" rule.

**Comment by mkeeter** [comment]
You discovered the secret, forbidden technique: the validation layer only checks that moves share a row/column and that the resulting board is valid; it does not check whether the placed pieces are actually all connected.

This is fixed in the commit above, and I'll deploy a server change shortly.
