### ISSUE TITLE
Highlight just played tiles?

### ISSUE THREAD

**Issue by tbelaire** [mkeeter/pont#4]
It'd be nice if the just played tiles had a border around them.  

Maybe even each players tiles with their own colour?

**Comment by gjeuken** [comment]
Hi,
I use this to play with my mom, and she had the same suggestion.
The game would flow much better if the just played tiles were somehow differentiated from the rest. Maybe just a background colour change would suffice.
Ideally, this could also be combined with an audio cue when someone has finished their play, possibly with a different one when it is your turn #2.

Thanks for the excellent work and for giving me and my family some joy these days!

**Comment by mkeeter** [comment]
Merged in fd69a0159cc0501f6d3a9f5cbd25dbdcf56854ba, with more commentary in the #6 thread.
