### ISSUE TITLE
Add total of remaining tiles

### ISSUE THREAD

**Issue by Khk2021** [mkeeter/pont#8]
In the physical game, you can see the bag with the tiles, so you know when it is getting low. If you make the space where the "swap tiles" box is smaller, you could add a counter there which showed how many tiles remain in the bag.

**Comment by mkeeter** [comment]
Done in c0ad16e7738f31625542704fcc574dedcc00b5a8

**Comment by Khk2021** [comment]
KarenOn May 22, 2023, at 10:38 AM, Matt Keeter ***@***.***> wrote:﻿
Closed #8 as completed.
