### ISSUE TITLE
Allow player to move the tiles around on their tile rack

### ISSUE THREAD

**Issue by Khk2021** [mkeeter/pont#9]
we often want to be able to move tiles next to each other so we can remember that we are saving them for a specific move, or that they are to be used in the next move etc. So it would be good if we could move the tiles around while we are waiting for our turn.

**Comment by mkeeter** [comment]
HI MOM!

Done in e6c7fba58257fc6af3434b1c372978f990776a40

**Comment by Khk2021** [comment]
AWESOME!! 
XOXO
Mom
